"""AuditRecord: a minimal, deterministic trace of one grounded question
asked through POST /api/patients/{patient_id}/ask (Phase 7).

This is NOT a new source of clinical truth. It is a receipt of what the
existing pipeline (Phases 5E-6G) already established: GroundedContext's
retrieval status, GroundedAnswer's final validated status, and which
Evidence items — by traceable identifier only, never their clinical
content — actually backed the delivered answer. Every field here is a
direct copy of a value the pipeline had already produced; nothing is
inferred, scored, or generated by this module.

Mirrors the same patient-isolation validator pattern already established by
RetrievalResult (app/models/retrieval.py), GroundedContext
(app/models/rag_context.py), and GroundedAnswer (app/models/answer.py): an
AuditRecord literally cannot be constructed with an evidence reference
belonging to a different patient than the record itself.

Deliberately excluded, even though a future implementation might be
tempted to add them: raw FHIR, raw MongoDB documents, the LLM's raw
generated text, prompts, chain-of-thought/hidden reasoning, confidence/
hallucination/probability scores, API keys, or any other secret.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field, model_validator

from app.models.answer import AnswerStatus
from app.models.retrieval import RetrievalStatus
from app.models.schemas import PaginationMeta


class AuditEvidenceReference(BaseModel):
    """A traceable pointer only — resource_type/resource_id, never the
    clinical value, display text, or any other content of the Evidence
    item it points back to. `patient_id` is carried here so AuditRecord's
    own validator (below) can enforce isolation structurally; it is
    stripped back out before the record is exposed via the API (see
    AuditRecordOut / AuditEvidenceReferenceOut)."""

    patient_id: str = Field(..., min_length=1)
    resource_type: str = Field(..., min_length=1)
    resource_id: str = Field(..., min_length=1)


class AuditRecord(BaseModel):
    """One immutable audit-trail entry: what was asked, what retrieval
    found, what the final validated answer status was, and which evidence
    (by identifier only) actually backed it."""

    audit_id: str = Field(..., min_length=1)
    patient_id: str = Field(..., min_length=1)
    query: str = Field(..., min_length=1)
    retrieval_status: RetrievalStatus
    answer_status: AnswerStatus
    evidence_references: list[AuditEvidenceReference] = []
    created_at: datetime

    @model_validator(mode="after")
    def _validate_evidence_belongs_to_requested_patient(self) -> "AuditRecord":
        mismatched = [e for e in self.evidence_references if e.patient_id != self.patient_id]
        if mismatched:
            raise ValueError(
                f"AuditRecord for patient '{self.patient_id}' contains an evidence reference belonging to a "
                f"different patient ('{mismatched[0].patient_id}') — cross-patient evidence is not permitted"
            )
        return self


class AuditEvidenceReferenceOut(BaseModel):
    """The API-facing view of one evidence reference — identifiers only, no
    patient_id (the enclosing record is already patient-scoped by the URL)."""

    resource_type: str
    resource_id: str


class AuditRecordOut(BaseModel):
    """The API-facing view of one AuditRecord — identical fields, but with
    patient_id dropped from each evidence reference."""

    audit_id: str
    patient_id: str
    query: str
    retrieval_status: RetrievalStatus
    answer_status: AnswerStatus
    evidence_references: list[AuditEvidenceReferenceOut]
    created_at: datetime

    @classmethod
    def from_record(cls, record: AuditRecord) -> "AuditRecordOut":
        return cls(
            audit_id=record.audit_id,
            patient_id=record.patient_id,
            query=record.query,
            retrieval_status=record.retrieval_status,
            answer_status=record.answer_status,
            evidence_references=[
                AuditEvidenceReferenceOut(resource_type=e.resource_type, resource_id=e.resource_id)
                for e in record.evidence_references
            ],
            created_at=record.created_at,
        )


class AuditHistoryOut(BaseModel):
    """GET /api/patients/{patient_id}/audit's response shape — mirrors the
    existing EvidenceListOut/ResourceListOut pagination convention
    (app/models/schemas.py) rather than inventing a new one."""

    items: list[AuditRecordOut]
    pagination: PaginationMeta
